WEB_DIRECTORY = "./js"
CSS_DIRECTORY = "./css"

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "WEB_DIRECTORY",
    "CSS_DIRECTORY",
]

from .MultiIntNode import (
    NODE_CLASS_MAPPINGS as MULTIINT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MULTIINT_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {**MULTIINT_NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**MULTIINT_DISPLAY_NAME_MAPPINGS}
