# __init__.py

WEB_DIRECTORY = "./js"
CSS_DIRECTORY = "./css"

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "WEB_DIRECTORY",
    "CSS_DIRECTORY",
]

from .MultiIntNode import (
    NODE_CLASS_MAPPINGS as MULTIINT_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MULTIINT_DISPLAY_NAME_MAPPINGS,
)

from .MultiText import (
    NODE_CLASS_MAPPINGS as MULTITEXT_NODE_CLASS_MAPPINGS,  # Import the class mappings for MultiText
    NODE_DISPLAY_NAME_MAPPINGS as MULTITEXT_DISPLAY_NAME_MAPPINGS,  # Import the display name mappings
)

# Combine the mappings from both MultiInt and MultiText nodes
NODE_CLASS_MAPPINGS = {**MULTIINT_NODE_CLASS_MAPPINGS, **MULTITEXT_NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**MULTIINT_DISPLAY_NAME_MAPPINGS, **MULTITEXT_DISPLAY_NAME_MAPPINGS}
